// All plants
http://localhost:3000/api/plants
###
// One plant
http://localhost:3000/api/plants/2
###
// User Profil
http://localhost:3000/api/users/1
###
// All culture in-progress for one user
http://localhost:3000/api/users/1/cultures/in-progress
###
// All culture completed for one user
http://localhost:3000/api/users/1/cultures/completed
###
// All culture by plot in progress
http://localhost:3000/api/users/2/cultures/plots/36
###
// All culture by culture in progress
http://localhost:3000/api/users/1/cultures/2
###
// The last categories
http://localhost:3000/api/users/1/cultures/plots/1/last-cultures
###
// Alliance
http://localhost:3000/api/users/4/plots/11/alliances
###
PUT http://localhost:3000/api/plants/60
Content-Type: application/json

{
  "name": "Blé",
  "id_category": 1
}
### Post a new category
PUT http://localhost:3000/api/plants/categories/3
Content-Type: application/json

{
  "name": "test"
}
###
### Post a new family
PUT http://localhost:3000/api/plants/families/1
Content-Type: application/json

{
  "name": "drgwname",
  "id_alliance": 2
}
###
### Post a new alliance
PUT http://localhost:3000/api/plants/alliances/7
Content-Type: application/json

{
  "alliance": [4]
}
###
### Post a new plot
POST http://localhost:3000/api/users/2/plots
Content-Type: application/json

{
  "name": "test",
  "availability": true,
  "id_user": 3
}
###
### Post a new culture
POST http://localhost:3000/api/users/2/cultures
Content-Type: application/json

{
  "sowing": "2023-06-01",
  "id_plant": 4,
  "id_plot": 8,
  "comment": "This is a test culture."
}
###
