// All plants
http://localhost:3000/api/plants
###
// One plant
http://localhost:3000/api/plants/2
###
// User Profil
http://localhost:3000/api/users/1
###
// All culture in-progress for one user
http://localhost:3000/api/users/1/cultures/in-progress
###
// All culture completed for one user
http://localhost:3000/api/users/1/cultures/completed
###
// All culture by plot in progress
http://localhost:3000/api/users/2/cultures/plots/6
###
// All culture by culture in progress
http://localhost:3000/api/users/1/cultures/2
###
// The last categories
http://localhost:3000/api/users/1/cultures/plots/1/last-cultures
###
// Alliance
http://localhost:3000/api/users/4/plots/11/alliances
###
### Post a new plant
POST http://localhost:3000/api/plants
Content-Type: application/json

{
  "name": "Rose",
  "specification": ["Thorny", "Blooms in summer"],
  "culture_advice": ["Needs lots of sunlight", "Water regularly"],
  "id_family": 1,
  "id_category": 1
}
### Post a new category
POST http://localhost:3000/api/plants/categories
Content-Type: application/json

{
  "name": "new category name"
}
###
### Post a new family
POST http://localhost:3000/api/plants/families
Content-Type: application/json

{
  "name": "new family name",
  "id_alliance": 1
}
###
### Post a new alliance
POST http://localhost:3000/api/plants/alliance
Content-Type: application/json

{
  "alliance": [1, 3], // This should be an array of family IDs
}
###
